apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    volumeMounts:
      - mountPath: /volume-dentro-do-container
        name: primeiro-volume
    ports:
      - containerPort: <Port>
  volumes:
    - name: primeiro-volume
      hostPath:
        path: /Users/israelmendesdasilva/Desktop/personal/code/kubernetes-courses/alura-course-02/project/volume
        type: Directory
